/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./src/context"
import type { core } from "nexus"
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    /**
     * A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    dateTime<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "DateTime";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    dateTime<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "DateTime";
  }
}


declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  IndikatorInputType: { // input type
    branch_kd: string; // String!
    definisi: string; // String!
    is_benefit: string; // String!
    nama: string; // String!
  }
  IndikatorNestedInputType: { // input type
    bobot?: number | null; // Float
    branch_kd: string; // String!
    definisi: string; // String!
    is_benefit: string; // String!
    kategori_id: string; // String!
    nama: string; // String!
    no_urut: number; // Int!
    perbandingan?: string | null; // String
  }
  JumPosisiPetugasKegSurveiInputType: { // input type
    branch_kd: string; // String!
    is_confirmed?: boolean | null; // Boolean
    jumlah: number; // Int!
    kategori_id: string; // String!
    keg_kd: string; // String!
    posisi_kd: string; // String!
    survei_kd: string; // String!
  }
  KategoriIndikatorInputType: { // input type
    bobot?: number | null; // Float
    branch_kd: string; // String!
    indikator_id: string; // String!
    kategori_id: string; // String!
    no_urut: number; // Int!
    perbandingan?: string | null; // String
  }
  KategoriInputType: { // input type
    definisi: string; // String!
    nama: string; // String!
  }
  KegSurveiInputType: { // input type
    is_add_indicator?: boolean | null; // Boolean
    is_confirm?: boolean | null; // Boolean
    is_multi?: number | null; // Int
    is_rekrutmen?: number | null; // Int
    keg_kd: string; // String!
    status: number; // Int!
    survei_kd: string; // String!
    tgl_buka?: NexusGenScalars['DateTime'] | null; // DateTime
    tgl_mulai?: NexusGenScalars['DateTime'] | null; // DateTime
    tgl_rek_mulai?: NexusGenScalars['DateTime'] | null; // DateTime
    tgl_rek_selesai?: NexusGenScalars['DateTime'] | null; // DateTime
    tgl_selesai?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  MitraTahunKerjaInputType: { // input type
    branch_kd: string; // String!
    status: number; // Int!
    tahun: string; // String!
    username: string; // String!
  }
  NilaiKategoriIndikatorInputType: { // input type
    branch_kd: string; // String!
    is_final: boolean; // Boolean!
    kategoriIndikator_id: Array<number | null>; // [Int]!
    keg_kd: string; // String!
    nilai: Array<number | null>; // [Int]!
    posisi_kd: string; // String!
    survei_kd: string; // String!
    tahun: string; // String!
    username: string; // String!
  }
  PenugasanStrukturInputType: { // input type
    branch_kd: string; // String!
    keg_kd: string; // String!
    parent?: string | null; // String
    posisi_kd: string; // String!
    status?: number | null; // Int
    username: string; // String!
  }
  PetugasKinerjaSurveiInputType: { // input type
    branch_kd: string; // String!
    keg_kd: string; // String!
    nilai?: number | null; // Int
    penilai: string; // String!
    posisi_kd: string; // String!
    survei_kd: string; // String!
  }
  PetugasSurveiInputType: { // input type
    branch_kd: string; // String!
    keg_kd: string; // String!
    posisi_kd: string; // String!
    status?: number | null; // Int
    survei_kd: string; // String!
    username: string; // String!
  }
  PosKegSurveiInputType: { // input type
    is_multi?: number | null; // Int
    is_view_mitra?: number | null; // Int
    keg_kd: string; // String!
    posisi_kd: string; // String!
    survei_kd: string; // String!
    urutan?: number | null; // Int
  }
  RankMitraInputType: { // input type
    branch_kd: string; // String!
    kategori_id: number; // Int!
    nilai: number; // Float!
    username: string; // String!
  }
  RankMitraPosKegSurveiInputType: { // input type
    branch_kd: string; // String!
    keg_kd: string; // String!
    nilai?: number | null; // Float
    posisi_kd: string; // String!
    survei_kd: string; // String!
    username: string; // String!
  }
  RankMitraTahunKerjaInputType: { // input type
    branch_kd: string; // String!
    keg_kd: string; // String!
    nilai?: number | null; // Float
    posisi_kd: string; // String!
    survei_kd: string; // String!
    tahun: string; // String!
    username: string; // String!
  }
  SurveiInputType: { // input type
    kode: string; // String!
    nama: string; // String!
    tahun: string; // String!
    tipe: number; // Int!
    unit_kd?: string | null; // String
  }
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  DateTime: any
}

export interface NexusGenObjects {
  AuthPayload: { // root type
    token: string; // String!
    user: NexusGenRootTypes['user']; // user!
  }
  Mutation: {};
  Query: {};
  indikator: { // root type
    branch_kd: string; // String!
    definisi: string; // String!
    indikator_id: string; // ID!
    is_benefit: number; // Int!
    nama: string; // String!
  }
  indikatorNested: { // root type
    KategoriIndikator: Array<NexusGenRootTypes['kategoriIndikator'] | null>; // [kategoriIndikator]!
    branch_kd: string; // String!
    definisi: string; // String!
    indikator_id: string; // ID!
    is_benefit: number; // Int!
    nama: string; // String!
  }
  indikatorNestedQuery: { // root type
    KategoriIndikator: Array<NexusGenRootTypes['kategoriIndikator'] | null>; // [kategoriIndikator]!
    branch_kd: string; // String!
    definisi: string; // String!
    indikator_id: string; // ID!
    is_benefit: number; // Int!
    nama: string; // String!
  }
  jumPosisiPetugasKegSurvei: { // root type
    Kegiatan: NexusGenRootTypes['kegiatan']; // kegiatan!
    Posisi: NexusGenRootTypes['posisi']; // posisi!
    Survei: NexusGenRootTypes['survei']; // survei!
    branch_kd: string; // String!
    is_confirmed?: boolean | null; // Boolean
    jumlah: number; // Int!
    jumposisipetugaskegsurvei_id: string; // ID!
    kategori: NexusGenRootTypes['kategori']; // kategori!
    kategori_id: string; // String!
    keg_kd: string; // String!
    posisi_kd: string; // String!
    survei_kd: string; // String!
    unit_kd?: string | null; // String
  }
  kategori: { // root type
    definisi: string; // String!
    kategori_id: string; // ID!
    nama: string; // String!
  }
  kategoriIndikator: { // root type
    bobot?: number | null; // Float
    branch_kd: string; // String!
    indikator?: NexusGenRootTypes['indikator'] | null; // indikator
    indikator_id: string; // ID!
    kategori?: NexusGenRootTypes['kategori'] | null; // kategori
    kategoriIndikator_id: string; // ID!
    kategori_id: string; // ID!
    no_urut: number; // Int!
    perbandingan?: string | null; // String
  }
  kegSurvei: { // root type
    Kegiatan: NexusGenRootTypes['kegiatan']; // kegiatan!
    Survei: NexusGenRootTypes['survei']; // survei!
    is_add_indicator?: boolean | null; // Boolean
    is_confirm?: boolean | null; // Boolean
    is_multi?: number | null; // Int
    is_rekrutmen?: number | null; // Int
    keg_kd: string; // String!
    kegsurvei_id: string; // ID!
    status: number; // Int!
    survei_kd: string; // String!
    tgl_buka?: NexusGenScalars['DateTime'] | null; // DateTime
    tgl_mulai?: NexusGenScalars['DateTime'] | null; // DateTime
    tgl_rek_mulai?: NexusGenScalars['DateTime'] | null; // DateTime
    tgl_rek_selesai?: NexusGenScalars['DateTime'] | null; // DateTime
    tgl_selesai?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  kegiatan: { // root type
    deskripsi: string; // String!
    kegiatan_id: string; // ID!
    kode: string; // String!
    nama: string; // String!
    status: number; // Int!
  }
  mitraTahunKerja: { // root type
    branch_kd: string; // String!
    mitratahunkerja_id: string; // ID!
    status: number; // Int!
    tahun: string; // String!
    username: string; // String!
  }
  nilaiKategoriIndikator: { // root type
    branch_kd: string; // String!
    is_final: boolean; // Boolean!
    kategoriIndikator_id: number; // Int!
    keg_kd: string; // String!
    nilai?: number | null; // Int
    nilaikategoriindikator_id: string; // ID!
    posisi_kd: string; // String!
    survei_kd: string; // String!
    tahun: string; // String!
    username: string; // String!
  }
  penugasanStruktur: { // root type
    branch_kd: string; // String!
    keg_kd: string; // String!
    parent: string; // String!
    penugasanstruktur_id: string; // ID!
    posisi_kd: string; // String!
    status: number; // Int!
    username: string; // String!
  }
  petugasKinerjaSurvei: { // root type
    branch_kd: string; // String!
    keg_kd: string; // String!
    nilai: number; // Int!
    penilai: string; // String!
    petugaskinerjasurvei_id: string; // ID!
    posisi_kd: string; // String!
    survei_kd: string; // String!
  }
  petugasSurvei: { // root type
    branch_kd: string; // String!
    keg_kd: string; // String!
    petugassurvei_id: string; // ID!
    posisi_kd: string; // String!
    status?: number | null; // Int
    survei_kd: string; // String!
    username: string; // String!
  }
  posKegSurvei: { // root type
    is_multi?: number | null; // Int
    is_view_mitra?: number | null; // Int
    keg_kd: string; // String!
    posisi_kd: string; // String!
    poskegsurvei_id: string; // ID!
    survei_kd: string; // String!
    urutan?: number | null; // Int
  }
  posisi: { // root type
    deskripsi: string; // String!
    kode: string; // String!
    nama: string; // String!
    posisi_id: string; // ID!
    status: number; // Int!
  }
  rankMitra: { // root type
    branch_kd: string; // String!
    kategori: NexusGenRootTypes['kategori']; // kategori!
    kategori_id: string; // String!
    nilai: number; // Float!
    rankmitra_id: string; // ID!
    username: string; // String!
  }
  rankMitraPosKegSurvei: { // root type
    branch_kd: string; // String!
    keg_kd: string; // String!
    nilai: number; // Float!
    posisi_kd: string; // String!
    rankmitraposkegsurvei_id: string; // ID!
    survei_kd: string; // String!
    username: string; // String!
  }
  rankMitraTahunKerja: { // root type
    branch_kd: string; // String!
    keg_kd: string; // String!
    nilai: number; // Float!
    posisi_kd: string; // String!
    rankmitratahunkerja_id: string; // ID!
    survei_kd: string; // String!
    tahun: string; // String!
    username: string; // String!
  }
  survei: { // root type
    kode: string; // String!
    nama: string; // String!
    survei_id: string; // ID!
    tahun: string; // String!
    tipe: number; // Int!
    unit_kd?: string | null; // String
  }
  user: { // root type
    email: string; // String!
    is_pegawai?: boolean | null; // Boolean
    nama?: string | null; // String
    user_id: string; // ID!
    username: string; // String!
  }
  userRole: { // root type
    role_id: number; // Int!
    status?: number | null; // Int
    user_role_id: string; // ID!
    username?: string | null; // String
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  AuthPayload: { // field return type
    token: string; // String!
    user: NexusGenRootTypes['user']; // user!
  }
  Mutation: { // field return type
    createIndikator: NexusGenRootTypes['indikator']; // indikator!
    createIndikatorNested: NexusGenRootTypes['indikatorNested']; // indikatorNested!
    createJumPosisiPetugasKegSurvei: NexusGenRootTypes['jumPosisiPetugasKegSurvei']; // jumPosisiPetugasKegSurvei!
    createKategori: NexusGenRootTypes['kategori']; // kategori!
    createKategoriIndikator: NexusGenRootTypes['kategoriIndikator']; // kategoriIndikator!
    createKegSurvei: NexusGenRootTypes['kegSurvei']; // kegSurvei!
    createKegiatan: NexusGenRootTypes['kegiatan']; // kegiatan!
    createManyPenugasanStruktur: Array<NexusGenRootTypes['penugasanStruktur'] | null>; // [penugasanStruktur]!
    createManyPetugasSurvei: Array<NexusGenRootTypes['petugasSurvei'] | null>; // [petugasSurvei]!
    createMitraTahunKerja: NexusGenRootTypes['mitraTahunKerja']; // mitraTahunKerja!
    createNilaiKategoriIndikator: NexusGenRootTypes['nilaiKategoriIndikator'][]; // [nilaiKategoriIndikator!]!
    createPenugasanStruktur: NexusGenRootTypes['penugasanStruktur']; // penugasanStruktur!
    createPetugasKinerjaSurvei: NexusGenRootTypes['petugasKinerjaSurvei']; // petugasKinerjaSurvei!
    createPetugasSurvei: NexusGenRootTypes['petugasSurvei']; // petugasSurvei!
    createPosKegSurvei: NexusGenRootTypes['posKegSurvei']; // posKegSurvei!
    createPosisi: NexusGenRootTypes['posisi']; // posisi!
    createRankMitra: NexusGenRootTypes['rankMitra']; // rankMitra!
    createRankMitraPosKegSurvei: NexusGenRootTypes['rankMitraPosKegSurvei']; // rankMitraPosKegSurvei!
    createRankMitraTahunKerja: NexusGenRootTypes['rankMitraTahunKerja']; // rankMitraTahunKerja!
    createSurvei: NexusGenRootTypes['survei']; // survei!
    createUserRole: NexusGenRootTypes['userRole']; // userRole!
    deleteIndikator: NexusGenRootTypes['indikator'] | null; // indikator
    deleteKategori: NexusGenRootTypes['kategori'] | null; // kategori
    deleteKategoriIndikator: NexusGenRootTypes['kategoriIndikator'] | null; // kategoriIndikator
    login: NexusGenRootTypes['AuthPayload']; // AuthPayload!
    signup: NexusGenRootTypes['AuthPayload']; // AuthPayload!
    updateIndikator: NexusGenRootTypes['indikator']; // indikator!
    updateJumPosisiPetugasKegSurvei: NexusGenRootTypes['jumPosisiPetugasKegSurvei']; // jumPosisiPetugasKegSurvei!
    updateKategori: NexusGenRootTypes['kategori']; // kategori!
    updateKategoriIndikator: NexusGenRootTypes['kategoriIndikator']; // kategoriIndikator!
    updateNilaiKategoriIndikator: NexusGenRootTypes['nilaiKategoriIndikator'][]; // [nilaiKategoriIndikator!]!
    updateRankMitra: NexusGenRootTypes['rankMitra']; // rankMitra!
    updateRankMitraPosKegSurvei: NexusGenRootTypes['rankMitraPosKegSurvei']; // rankMitraPosKegSurvei!
    updateRankMitraTahunKerja: NexusGenRootTypes['rankMitraTahunKerja']; // rankMitraTahunKerja!
  }
  Query: { // field return type
    JumPosisiPetugasKegSurvei: Array<NexusGenRootTypes['jumPosisiPetugasKegSurvei'] | null>; // [jumPosisiPetugasKegSurvei]!
    Kategori: NexusGenRootTypes['kategori']; // kategori!
    KegSurvei: Array<NexusGenRootTypes['kegSurvei'] | null>; // [kegSurvei]!
    Kegiatan: Array<NexusGenRootTypes['kegiatan'] | null>; // [kegiatan]!
    MitraTahunKerja: Array<NexusGenRootTypes['mitraTahunKerja'] | null>; // [mitraTahunKerja]!
    NilaiKategoriIndikator: Array<NexusGenRootTypes['nilaiKategoriIndikator'] | null>; // [nilaiKategoriIndikator]!
    PenugasanStruktur: Array<NexusGenRootTypes['penugasanStruktur'] | null>; // [penugasanStruktur]!
    PetugasKinerjaSurvei: Array<NexusGenRootTypes['petugasKinerjaSurvei'] | null>; // [petugasKinerjaSurvei]!
    PetugasSurvei: Array<NexusGenRootTypes['petugasSurvei'] | null>; // [petugasSurvei]!
    PosKegSurvei: Array<NexusGenRootTypes['posKegSurvei'] | null>; // [posKegSurvei]!
    Posisi: Array<NexusGenRootTypes['posisi'] | null>; // [posisi]!
    RankMitra: Array<NexusGenRootTypes['rankMitra'] | null>; // [rankMitra]!
    RankMitraPosKegSurvei: Array<NexusGenRootTypes['rankMitraPosKegSurvei'] | null>; // [rankMitraPosKegSurvei]!
    RankMitraTahunKerja: Array<NexusGenRootTypes['rankMitraTahunKerja'] | null>; // [rankMitraTahunKerja]!
    Survei: Array<NexusGenRootTypes['survei'] | null>; // [survei]!
    allIndikatorNested: NexusGenRootTypes['indikatorNestedQuery'][]; // [indikatorNestedQuery!]!
    allKategori: NexusGenRootTypes['kategori'][]; // [kategori!]!
    allKategoriIndikator: NexusGenRootTypes['kategoriIndikator'][]; // [kategoriIndikator!]!
    countSearchPenugasanStruktur: number; // Int!
    indikator: NexusGenRootTypes['indikator'][]; // [indikator!]!
    kategoriIndikator: NexusGenRootTypes['kategoriIndikator']; // kategoriIndikator!
    searchJumPosisiPetugasKegSurvei: Array<NexusGenRootTypes['jumPosisiPetugasKegSurvei'] | null>; // [jumPosisiPetugasKegSurvei]!
    searchPenugasanStruktur: Array<NexusGenRootTypes['penugasanStruktur'] | null>; // [penugasanStruktur]!
    someIndikator: NexusGenRootTypes['indikator'][]; // [indikator!]!
  }
  indikator: { // field return type
    branch_kd: string; // String!
    definisi: string; // String!
    indikator_id: string; // ID!
    is_benefit: number; // Int!
    nama: string; // String!
  }
  indikatorNested: { // field return type
    KategoriIndikator: Array<NexusGenRootTypes['kategoriIndikator'] | null>; // [kategoriIndikator]!
    branch_kd: string; // String!
    definisi: string; // String!
    indikator_id: string; // ID!
    is_benefit: number; // Int!
    nama: string; // String!
  }
  indikatorNestedQuery: { // field return type
    KategoriIndikator: Array<NexusGenRootTypes['kategoriIndikator'] | null>; // [kategoriIndikator]!
    branch_kd: string; // String!
    definisi: string; // String!
    indikator_id: string; // ID!
    is_benefit: number; // Int!
    nama: string; // String!
  }
  jumPosisiPetugasKegSurvei: { // field return type
    Kegiatan: NexusGenRootTypes['kegiatan']; // kegiatan!
    Posisi: NexusGenRootTypes['posisi']; // posisi!
    Survei: NexusGenRootTypes['survei']; // survei!
    branch_kd: string; // String!
    is_confirmed: boolean | null; // Boolean
    jumlah: number; // Int!
    jumposisipetugaskegsurvei_id: string; // ID!
    kategori: NexusGenRootTypes['kategori']; // kategori!
    kategori_id: string; // String!
    keg_kd: string; // String!
    posisi_kd: string; // String!
    survei_kd: string; // String!
    unit_kd: string | null; // String
  }
  kategori: { // field return type
    KategoriIndikator: Array<NexusGenRootTypes['kategoriIndikator'] | null> | null; // [kategoriIndikator]
    definisi: string; // String!
    kategori_id: string; // ID!
    nama: string; // String!
  }
  kategoriIndikator: { // field return type
    bobot: number | null; // Float
    branch_kd: string; // String!
    indikator: NexusGenRootTypes['indikator'] | null; // indikator
    indikator_id: string; // ID!
    kategori: NexusGenRootTypes['kategori'] | null; // kategori
    kategoriIndikator_id: string; // ID!
    kategori_id: string; // ID!
    no_urut: number; // Int!
    perbandingan: string | null; // String
  }
  kegSurvei: { // field return type
    Kegiatan: NexusGenRootTypes['kegiatan']; // kegiatan!
    Survei: NexusGenRootTypes['survei']; // survei!
    is_add_indicator: boolean | null; // Boolean
    is_confirm: boolean | null; // Boolean
    is_multi: number | null; // Int
    is_rekrutmen: number | null; // Int
    keg_kd: string; // String!
    kegsurvei_id: string; // ID!
    status: number; // Int!
    survei_kd: string; // String!
    tgl_buka: NexusGenScalars['DateTime'] | null; // DateTime
    tgl_mulai: NexusGenScalars['DateTime'] | null; // DateTime
    tgl_rek_mulai: NexusGenScalars['DateTime'] | null; // DateTime
    tgl_rek_selesai: NexusGenScalars['DateTime'] | null; // DateTime
    tgl_selesai: NexusGenScalars['DateTime'] | null; // DateTime
  }
  kegiatan: { // field return type
    deskripsi: string; // String!
    kegiatan_id: string; // ID!
    kode: string; // String!
    nama: string; // String!
    status: number; // Int!
  }
  mitraTahunKerja: { // field return type
    User: NexusGenRootTypes['user']; // user!
    branch_kd: string; // String!
    mitratahunkerja_id: string; // ID!
    status: number; // Int!
    tahun: string; // String!
    username: string; // String!
  }
  nilaiKategoriIndikator: { // field return type
    KategoriIndikator: Array<NexusGenRootTypes['kategoriIndikator'] | null> | null; // [kategoriIndikator]
    Kegiatan: NexusGenRootTypes['kegiatan']; // kegiatan!
    Posisi: NexusGenRootTypes['posisi']; // posisi!
    Survei: NexusGenRootTypes['survei']; // survei!
    User: NexusGenRootTypes['user']; // user!
    branch_kd: string; // String!
    is_final: boolean; // Boolean!
    kategoriIndikator_id: number; // Int!
    keg_kd: string; // String!
    nilai: number | null; // Int
    nilaikategoriindikator_id: string; // ID!
    posisi_kd: string; // String!
    survei_kd: string; // String!
    tahun: string; // String!
    username: string; // String!
  }
  penugasanStruktur: { // field return type
    Kegiatan: NexusGenRootTypes['kegiatan']; // kegiatan!
    Posisi: NexusGenRootTypes['posisi']; // posisi!
    User: NexusGenRootTypes['user']; // user!
    branch_kd: string; // String!
    keg_kd: string; // String!
    parent: string; // String!
    penugasanstruktur_id: string; // ID!
    posisi_kd: string; // String!
    status: number; // Int!
    username: string; // String!
  }
  petugasKinerjaSurvei: { // field return type
    Kegiatan: NexusGenRootTypes['kegiatan']; // kegiatan!
    Posisi: NexusGenRootTypes['posisi']; // posisi!
    Survei: NexusGenRootTypes['survei']; // survei!
    User: NexusGenRootTypes['user']; // user!
    branch_kd: string; // String!
    keg_kd: string; // String!
    nilai: number; // Int!
    penilai: string; // String!
    petugaskinerjasurvei_id: string; // ID!
    posisi_kd: string; // String!
    survei_kd: string; // String!
  }
  petugasSurvei: { // field return type
    Kegiatan: NexusGenRootTypes['kegiatan']; // kegiatan!
    Posisi: NexusGenRootTypes['posisi']; // posisi!
    Survei: NexusGenRootTypes['survei']; // survei!
    User: NexusGenRootTypes['user']; // user!
    branch_kd: string; // String!
    keg_kd: string; // String!
    petugassurvei_id: string; // ID!
    posisi_kd: string; // String!
    status: number | null; // Int
    survei_kd: string; // String!
    username: string; // String!
  }
  posKegSurvei: { // field return type
    Kegiatan: NexusGenRootTypes['kegiatan']; // kegiatan!
    Posisi: NexusGenRootTypes['posisi']; // posisi!
    Survei: NexusGenRootTypes['survei']; // survei!
    is_multi: number | null; // Int
    is_view_mitra: number | null; // Int
    keg_kd: string; // String!
    posisi_kd: string; // String!
    poskegsurvei_id: string; // ID!
    survei_kd: string; // String!
    urutan: number | null; // Int
  }
  posisi: { // field return type
    deskripsi: string; // String!
    kode: string; // String!
    nama: string; // String!
    posisi_id: string; // ID!
    status: number; // Int!
  }
  rankMitra: { // field return type
    User: NexusGenRootTypes['user']; // user!
    branch_kd: string; // String!
    kategori: NexusGenRootTypes['kategori']; // kategori!
    kategori_id: string; // String!
    nilai: number; // Float!
    rankmitra_id: string; // ID!
    username: string; // String!
  }
  rankMitraPosKegSurvei: { // field return type
    Kegiatan: NexusGenRootTypes['kegiatan']; // kegiatan!
    Posisi: NexusGenRootTypes['posisi']; // posisi!
    Survei: NexusGenRootTypes['survei']; // survei!
    User: NexusGenRootTypes['user']; // user!
    branch_kd: string; // String!
    keg_kd: string; // String!
    nilai: number; // Float!
    posisi_kd: string; // String!
    rankmitraposkegsurvei_id: string; // ID!
    survei_kd: string; // String!
    username: string; // String!
  }
  rankMitraTahunKerja: { // field return type
    Kegiatan: NexusGenRootTypes['kegiatan']; // kegiatan!
    Posisi: NexusGenRootTypes['posisi']; // posisi!
    Survei: NexusGenRootTypes['survei']; // survei!
    User: NexusGenRootTypes['user']; // user!
    branch_kd: string; // String!
    keg_kd: string; // String!
    nilai: number; // Float!
    posisi_kd: string; // String!
    rankmitratahunkerja_id: string; // ID!
    survei_kd: string; // String!
    tahun: string; // String!
    username: string; // String!
  }
  survei: { // field return type
    kode: string; // String!
    nama: string; // String!
    survei_id: string; // ID!
    tahun: string; // String!
    tipe: number; // Int!
    unit_kd: string | null; // String
  }
  user: { // field return type
    MitraTahunKerja: Array<NexusGenRootTypes['mitraTahunKerja'] | null> | null; // [mitraTahunKerja]
    UserRole: Array<NexusGenRootTypes['userRole'] | null> | null; // [userRole]
    email: string; // String!
    is_pegawai: boolean | null; // Boolean
    nama: string | null; // String
    user_id: string; // ID!
    username: string; // String!
  }
  userRole: { // field return type
    role_id: number; // Int!
    status: number | null; // Int
    user_role_id: string; // ID!
    username: string | null; // String
  }
}

export interface NexusGenFieldTypeNames {
  AuthPayload: { // field return type name
    token: 'String'
    user: 'user'
  }
  Mutation: { // field return type name
    createIndikator: 'indikator'
    createIndikatorNested: 'indikatorNested'
    createJumPosisiPetugasKegSurvei: 'jumPosisiPetugasKegSurvei'
    createKategori: 'kategori'
    createKategoriIndikator: 'kategoriIndikator'
    createKegSurvei: 'kegSurvei'
    createKegiatan: 'kegiatan'
    createManyPenugasanStruktur: 'penugasanStruktur'
    createManyPetugasSurvei: 'petugasSurvei'
    createMitraTahunKerja: 'mitraTahunKerja'
    createNilaiKategoriIndikator: 'nilaiKategoriIndikator'
    createPenugasanStruktur: 'penugasanStruktur'
    createPetugasKinerjaSurvei: 'petugasKinerjaSurvei'
    createPetugasSurvei: 'petugasSurvei'
    createPosKegSurvei: 'posKegSurvei'
    createPosisi: 'posisi'
    createRankMitra: 'rankMitra'
    createRankMitraPosKegSurvei: 'rankMitraPosKegSurvei'
    createRankMitraTahunKerja: 'rankMitraTahunKerja'
    createSurvei: 'survei'
    createUserRole: 'userRole'
    deleteIndikator: 'indikator'
    deleteKategori: 'kategori'
    deleteKategoriIndikator: 'kategoriIndikator'
    login: 'AuthPayload'
    signup: 'AuthPayload'
    updateIndikator: 'indikator'
    updateJumPosisiPetugasKegSurvei: 'jumPosisiPetugasKegSurvei'
    updateKategori: 'kategori'
    updateKategoriIndikator: 'kategoriIndikator'
    updateNilaiKategoriIndikator: 'nilaiKategoriIndikator'
    updateRankMitra: 'rankMitra'
    updateRankMitraPosKegSurvei: 'rankMitraPosKegSurvei'
    updateRankMitraTahunKerja: 'rankMitraTahunKerja'
  }
  Query: { // field return type name
    JumPosisiPetugasKegSurvei: 'jumPosisiPetugasKegSurvei'
    Kategori: 'kategori'
    KegSurvei: 'kegSurvei'
    Kegiatan: 'kegiatan'
    MitraTahunKerja: 'mitraTahunKerja'
    NilaiKategoriIndikator: 'nilaiKategoriIndikator'
    PenugasanStruktur: 'penugasanStruktur'
    PetugasKinerjaSurvei: 'petugasKinerjaSurvei'
    PetugasSurvei: 'petugasSurvei'
    PosKegSurvei: 'posKegSurvei'
    Posisi: 'posisi'
    RankMitra: 'rankMitra'
    RankMitraPosKegSurvei: 'rankMitraPosKegSurvei'
    RankMitraTahunKerja: 'rankMitraTahunKerja'
    Survei: 'survei'
    allIndikatorNested: 'indikatorNestedQuery'
    allKategori: 'kategori'
    allKategoriIndikator: 'kategoriIndikator'
    countSearchPenugasanStruktur: 'Int'
    indikator: 'indikator'
    kategoriIndikator: 'kategoriIndikator'
    searchJumPosisiPetugasKegSurvei: 'jumPosisiPetugasKegSurvei'
    searchPenugasanStruktur: 'penugasanStruktur'
    someIndikator: 'indikator'
  }
  indikator: { // field return type name
    branch_kd: 'String'
    definisi: 'String'
    indikator_id: 'ID'
    is_benefit: 'Int'
    nama: 'String'
  }
  indikatorNested: { // field return type name
    KategoriIndikator: 'kategoriIndikator'
    branch_kd: 'String'
    definisi: 'String'
    indikator_id: 'ID'
    is_benefit: 'Int'
    nama: 'String'
  }
  indikatorNestedQuery: { // field return type name
    KategoriIndikator: 'kategoriIndikator'
    branch_kd: 'String'
    definisi: 'String'
    indikator_id: 'ID'
    is_benefit: 'Int'
    nama: 'String'
  }
  jumPosisiPetugasKegSurvei: { // field return type name
    Kegiatan: 'kegiatan'
    Posisi: 'posisi'
    Survei: 'survei'
    branch_kd: 'String'
    is_confirmed: 'Boolean'
    jumlah: 'Int'
    jumposisipetugaskegsurvei_id: 'ID'
    kategori: 'kategori'
    kategori_id: 'String'
    keg_kd: 'String'
    posisi_kd: 'String'
    survei_kd: 'String'
    unit_kd: 'String'
  }
  kategori: { // field return type name
    KategoriIndikator: 'kategoriIndikator'
    definisi: 'String'
    kategori_id: 'ID'
    nama: 'String'
  }
  kategoriIndikator: { // field return type name
    bobot: 'Float'
    branch_kd: 'String'
    indikator: 'indikator'
    indikator_id: 'ID'
    kategori: 'kategori'
    kategoriIndikator_id: 'ID'
    kategori_id: 'ID'
    no_urut: 'Int'
    perbandingan: 'String'
  }
  kegSurvei: { // field return type name
    Kegiatan: 'kegiatan'
    Survei: 'survei'
    is_add_indicator: 'Boolean'
    is_confirm: 'Boolean'
    is_multi: 'Int'
    is_rekrutmen: 'Int'
    keg_kd: 'String'
    kegsurvei_id: 'ID'
    status: 'Int'
    survei_kd: 'String'
    tgl_buka: 'DateTime'
    tgl_mulai: 'DateTime'
    tgl_rek_mulai: 'DateTime'
    tgl_rek_selesai: 'DateTime'
    tgl_selesai: 'DateTime'
  }
  kegiatan: { // field return type name
    deskripsi: 'String'
    kegiatan_id: 'ID'
    kode: 'String'
    nama: 'String'
    status: 'Int'
  }
  mitraTahunKerja: { // field return type name
    User: 'user'
    branch_kd: 'String'
    mitratahunkerja_id: 'ID'
    status: 'Int'
    tahun: 'String'
    username: 'String'
  }
  nilaiKategoriIndikator: { // field return type name
    KategoriIndikator: 'kategoriIndikator'
    Kegiatan: 'kegiatan'
    Posisi: 'posisi'
    Survei: 'survei'
    User: 'user'
    branch_kd: 'String'
    is_final: 'Boolean'
    kategoriIndikator_id: 'Int'
    keg_kd: 'String'
    nilai: 'Int'
    nilaikategoriindikator_id: 'ID'
    posisi_kd: 'String'
    survei_kd: 'String'
    tahun: 'String'
    username: 'String'
  }
  penugasanStruktur: { // field return type name
    Kegiatan: 'kegiatan'
    Posisi: 'posisi'
    User: 'user'
    branch_kd: 'String'
    keg_kd: 'String'
    parent: 'String'
    penugasanstruktur_id: 'ID'
    posisi_kd: 'String'
    status: 'Int'
    username: 'String'
  }
  petugasKinerjaSurvei: { // field return type name
    Kegiatan: 'kegiatan'
    Posisi: 'posisi'
    Survei: 'survei'
    User: 'user'
    branch_kd: 'String'
    keg_kd: 'String'
    nilai: 'Int'
    penilai: 'String'
    petugaskinerjasurvei_id: 'ID'
    posisi_kd: 'String'
    survei_kd: 'String'
  }
  petugasSurvei: { // field return type name
    Kegiatan: 'kegiatan'
    Posisi: 'posisi'
    Survei: 'survei'
    User: 'user'
    branch_kd: 'String'
    keg_kd: 'String'
    petugassurvei_id: 'ID'
    posisi_kd: 'String'
    status: 'Int'
    survei_kd: 'String'
    username: 'String'
  }
  posKegSurvei: { // field return type name
    Kegiatan: 'kegiatan'
    Posisi: 'posisi'
    Survei: 'survei'
    is_multi: 'Int'
    is_view_mitra: 'Int'
    keg_kd: 'String'
    posisi_kd: 'String'
    poskegsurvei_id: 'ID'
    survei_kd: 'String'
    urutan: 'Int'
  }
  posisi: { // field return type name
    deskripsi: 'String'
    kode: 'String'
    nama: 'String'
    posisi_id: 'ID'
    status: 'Int'
  }
  rankMitra: { // field return type name
    User: 'user'
    branch_kd: 'String'
    kategori: 'kategori'
    kategori_id: 'String'
    nilai: 'Float'
    rankmitra_id: 'ID'
    username: 'String'
  }
  rankMitraPosKegSurvei: { // field return type name
    Kegiatan: 'kegiatan'
    Posisi: 'posisi'
    Survei: 'survei'
    User: 'user'
    branch_kd: 'String'
    keg_kd: 'String'
    nilai: 'Float'
    posisi_kd: 'String'
    rankmitraposkegsurvei_id: 'ID'
    survei_kd: 'String'
    username: 'String'
  }
  rankMitraTahunKerja: { // field return type name
    Kegiatan: 'kegiatan'
    Posisi: 'posisi'
    Survei: 'survei'
    User: 'user'
    branch_kd: 'String'
    keg_kd: 'String'
    nilai: 'Float'
    posisi_kd: 'String'
    rankmitratahunkerja_id: 'ID'
    survei_kd: 'String'
    tahun: 'String'
    username: 'String'
  }
  survei: { // field return type name
    kode: 'String'
    nama: 'String'
    survei_id: 'ID'
    tahun: 'String'
    tipe: 'Int'
    unit_kd: 'String'
  }
  user: { // field return type name
    MitraTahunKerja: 'mitraTahunKerja'
    UserRole: 'userRole'
    email: 'String'
    is_pegawai: 'Boolean'
    nama: 'String'
    user_id: 'ID'
    username: 'String'
  }
  userRole: { // field return type name
    role_id: 'Int'
    status: 'Int'
    user_role_id: 'ID'
    username: 'String'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    createIndikator: { // args
      input: NexusGenInputs['IndikatorInputType']; // IndikatorInputType!
    }
    createIndikatorNested: { // args
      input: NexusGenInputs['IndikatorNestedInputType']; // IndikatorNestedInputType!
    }
    createJumPosisiPetugasKegSurvei: { // args
      input: NexusGenInputs['JumPosisiPetugasKegSurveiInputType']; // JumPosisiPetugasKegSurveiInputType!
    }
    createKategori: { // args
      input: NexusGenInputs['KategoriInputType']; // KategoriInputType!
    }
    createKategoriIndikator: { // args
      input: NexusGenInputs['KategoriIndikatorInputType']; // KategoriIndikatorInputType!
    }
    createKegSurvei: { // args
      input: NexusGenInputs['KegSurveiInputType']; // KegSurveiInputType!
      survei?: NexusGenInputs['SurveiInputType'] | null; // SurveiInputType
    }
    createKegiatan: { // args
      deskripsi: string; // String!
      kode: string; // String!
      nama: string; // String!
      status: number; // Int!
    }
    createManyPenugasanStruktur: { // args
      input: NexusGenInputs['PenugasanStrukturInputType']; // PenugasanStrukturInputType!
      usernames: Array<string | null>; // [String]!
    }
    createManyPetugasSurvei: { // args
      input: NexusGenInputs['PetugasSurveiInputType']; // PetugasSurveiInputType!
      usernames: Array<string | null>; // [String]!
    }
    createMitraTahunKerja: { // args
      input: NexusGenInputs['MitraTahunKerjaInputType']; // MitraTahunKerjaInputType!
    }
    createNilaiKategoriIndikator: { // args
      input: NexusGenInputs['NilaiKategoriIndikatorInputType']; // NilaiKategoriIndikatorInputType!
    }
    createPenugasanStruktur: { // args
      input: NexusGenInputs['PenugasanStrukturInputType']; // PenugasanStrukturInputType!
    }
    createPetugasKinerjaSurvei: { // args
      input: NexusGenInputs['PetugasKinerjaSurveiInputType']; // PetugasKinerjaSurveiInputType!
    }
    createPetugasSurvei: { // args
      input: NexusGenInputs['PetugasSurveiInputType']; // PetugasSurveiInputType!
    }
    createPosKegSurvei: { // args
      input: NexusGenInputs['PosKegSurveiInputType']; // PosKegSurveiInputType!
    }
    createPosisi: { // args
      deskripsi: string; // String!
      kode: string; // String!
      nama: string; // String!
      status: number; // Int!
    }
    createRankMitra: { // args
      input: NexusGenInputs['RankMitraInputType']; // RankMitraInputType!
    }
    createRankMitraPosKegSurvei: { // args
      input: NexusGenInputs['RankMitraPosKegSurveiInputType']; // RankMitraPosKegSurveiInputType!
    }
    createRankMitraTahunKerja: { // args
      input: NexusGenInputs['RankMitraTahunKerjaInputType']; // RankMitraTahunKerjaInputType!
    }
    createSurvei: { // args
      input: NexusGenInputs['SurveiInputType']; // SurveiInputType!
    }
    createUserRole: { // args
      role_id: number; // Int!
      status: number; // Int!
      username: string; // String!
    }
    deleteIndikator: { // args
      id: number; // Int!
    }
    deleteKategori: { // args
      id: number; // Int!
    }
    deleteKategoriIndikator: { // args
      id: number; // Int!
    }
    login: { // args
      email: string; // String!
      password: string; // String!
    }
    signup: { // args
      email: string; // String!
      is_pegawai?: number | null; // Int
      nama: string; // String!
      password: string; // String!
      role_id: number; // Int!
      tahun: string; // String!
      username: string; // String!
    }
    updateIndikator: { // args
      id: number; // Int!
      input: NexusGenInputs['IndikatorInputType']; // IndikatorInputType!
    }
    updateJumPosisiPetugasKegSurvei: { // args
      id: number; // Int!
      is_confirmed?: boolean | null; // Boolean
      jumlah?: number | null; // Int
    }
    updateKategori: { // args
      id: number; // Int!
      input: NexusGenInputs['KategoriInputType']; // KategoriInputType!
    }
    updateKategoriIndikator: { // args
      id: number; // Int!
      input: NexusGenInputs['KategoriIndikatorInputType']; // KategoriIndikatorInputType!
    }
    updateNilaiKategoriIndikator: { // args
      id?: number | null; // Int
      input?: NexusGenInputs['NilaiKategoriIndikatorInputType'] | null; // NilaiKategoriIndikatorInputType
      is_final?: boolean | null; // Boolean
      nilai?: number | null; // Int
    }
    updateRankMitra: { // args
      id: number; // Int!
      input: NexusGenInputs['RankMitraInputType']; // RankMitraInputType!
    }
    updateRankMitraPosKegSurvei: { // args
      id: number; // Int!
      input: NexusGenInputs['RankMitraPosKegSurveiInputType']; // RankMitraPosKegSurveiInputType!
    }
    updateRankMitraTahunKerja: { // args
      id: number; // Int!
      input: NexusGenInputs['RankMitraTahunKerjaInputType']; // RankMitraTahunKerjaInputType!
    }
  }
  Query: {
    JumPosisiPetugasKegSurvei: { // args
      id?: number | null; // Int
    }
    Kategori: { // args
      id: number; // Int!
    }
    KegSurvei: { // args
      id?: number | null; // Int
      keg_kd?: string | null; // String
      survei_kd?: string | null; // String
    }
    Kegiatan: { // args
      kode?: string | null; // String
    }
    MitraTahunKerja: { // args
      id?: number | null; // Int
    }
    NilaiKategoriIndikator: { // args
      branch_kd?: string | null; // String
      id?: number | null; // Int
      keg_kd?: string | null; // String
      posisi_kd?: string | null; // String
      survei_kd?: string | null; // String
      tahun?: string | null; // String
      username?: string | null; // String
    }
    PenugasanStruktur: { // args
      branch_kd?: string | null; // String
      id?: number | null; // Int
      keg_kd?: string | null; // String
      posisi_kd?: string | null; // String
    }
    PetugasKinerjaSurvei: { // args
      id?: number | null; // Int
    }
    PetugasSurvei: { // args
      id?: number | null; // Int
      username?: string | null; // String
    }
    PosKegSurvei: { // args
      id?: number | null; // Int
    }
    Posisi: { // args
      kode?: string | null; // String
    }
    RankMitra: { // args
      branch_kd?: string | null; // String
      id?: number | null; // Int
      kategori_id?: string | null; // String
      username?: string | null; // String
    }
    RankMitraPosKegSurvei: { // args
      branch_kd?: string | null; // String
      id?: number | null; // Int
      keg_kd?: string | null; // String
      posisi_kd?: string | null; // String
      survei_kd?: string | null; // String
      username?: string | null; // String
    }
    RankMitraTahunKerja: { // args
      id?: number | null; // Int
    }
    Survei: { // args
      kode?: string | null; // String
    }
    countSearchPenugasanStruktur: { // args
      branch_kd: string; // String!
      keg_kd: string; // String!
      posisi_kd: string; // String!
    }
    indikator: { // args
      id?: number | null; // Int
    }
    kategoriIndikator: { // args
      id: number; // Int!
    }
    searchJumPosisiPetugasKegSurvei: { // args
      branch_kd: string; // String!
      keg_kd: string; // String!
      posisi_kd: string; // String!
      survei_kd: string; // String!
    }
    searchPenugasanStruktur: { // args
      branch_kd: string; // String!
      keg_kd: string; // String!
      posisi_kd: string; // String!
    }
    someIndikator: { // args
      id: number[]; // [Int!]!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}